#!/usr/bin/env bash
# install-faster-whisper.sh — 安装 faster-whisper（Python）作为 whisper-cli 替代。
#
# 用法：
#   sudo ./scripts/install-faster-whisper.sh
#

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

VENV_DIR="${1:-/opt/whisper-faster-venv}"
WRAPPER_SRC="$(cd "$(dirname "$0")" && pwd)/whisper-py-wrapper.py"
BIN_LINK="/usr/local/bin/whisper-cli"

echo -e "${GREEN}=== faster-whisper 安装脚本 ===${NC}"
echo ""

# ---------- Python 3 ----------
if ! command -v python3 &>/dev/null; then
    echo -e "${RED}未找到 python3，请先安装：sudo apt install -y python3 python3-venv python3-pip${NC}"
    exit 1
fi
PYVER=$(python3 -c 'import sys; vi=sys.version_info; print(f"{vi.major}.{vi.minor}")')
echo "[1/4] Python $PYVER 已检测"

# ---------- venv ----------
echo "[2/4] 创建虚拟环境: $VENV_DIR"
if [ -d "$VENV_DIR" ]; then
    echo -e "${YELLOW}  目录已存在，跳过创建（如需重装请先 rm -rf $VENV_DIR）${NC}"
else
    python3 -m venv "$VENV_DIR"
fi
source "$VENV_DIR/bin/activate"

# ---------- pip install ----------
echo "[3/4] 安装 faster-whisper ..."
pip install --upgrade pip setuptools wheel 2>&1 | tail -1
pip install faster-whisper 2>&1 | tail -3

# GPU 检查：有 nvidia-smi 才装 CUDA 包
if command -v nvidia-smi &>/dev/null; then
    echo "  检测到 N 卡，安装 CUDA 依赖 ..."
    pip install nvidia-cudnn-cu12 nvidia-cublas-cu12 2>&1 | tail -3 || true
    echo -e "${GREEN}  GPU 加速已就绪${NC}"
else
    echo -e "${YELLOW}  未检测到 nvidia-smi，跳过 CUDA 包（CPU only）${NC}"
fi

deactivate

# ---------- symlink ----------
echo "[4/4] 安装 wrapper → $BIN_LINK"
if [ -f "$BIN_LINK" ] && [ ! -L "$BIN_LINK" ]; then
    echo -e "${YELLOW}⚠ $BIN_LINK 已存在且不是符号链接。${NC}"
    echo "  如果是真正的 whisper.cpp 二进制，建议改个名（如 whisper-cli.cpp）再重新运行本脚本。"
    echo "  本脚本不会覆盖真正的二进制。"
    echo ""
    read -r -p "  要不要把它备份成 whisper-cli.cpp.bak 然后继续？[y/N] " ans
    if [ "$ans" = "y" ] || [ "$ans" = "Y" ]; then
        sudo mv "$BIN_LINK" "${BIN_LINK}.cpp.bak"
        echo "  已备份 → ${BIN_LINK}.cpp.bak"
    else
        echo "  跳过。安装完成后手动 ln -sf $WRAPPER_SRC $BIN_LINK"
        exit 0
    fi
fi

# 写入 wrapper 的 shebang 指向 venv python
cat <<'PYEOF' | sudo tee "$BIN_LINK" >/dev/null
#!/usr/bin/env bash
# Auto-generated by install-faster-whisper.sh
# This is a trampoline that calls the Python wrapper inside its venv.
WRAPPER="__WRAPPER_SRC__"
VENV_PYTHON="__VENV_PYTHON__"
exec "$VENV_PYTHON" "$WRAPPER" "$@"
PYEOF
sudo sed -i "s|__WRAPPER_SRC__|$WRAPPER_SRC|" "$BIN_LINK"
sudo sed -i "s|__VENV_PYTHON__|$VENV_DIR/bin/python3|" "$BIN_LINK"
sudo chmod +x "$BIN_LINK"

echo ""
echo -e "${GREEN}=================================================${NC}"
echo -e "${GREEN}  faster-whisper 安装完成！${NC}"
echo ""
echo "  wrapper 位置: $BIN_LINK"
echo "  Python venv:  $VENV_DIR"
echo ""
echo "  验证："
echo "    $BIN_LINK --help"
echo ""
echo "  在 Web UI「系统设置」中确认："
echo "    whisper-cli 路径 = whisper-cli（默认 PATH）"
echo "    使用 CUDA        = 开（有 N 卡时）"
echo -e "${GREEN}=================================================${NC}"
